FROM rust:1.91-slim AS builder

RUN apt-get update && apt-get install -y musl-tools
RUN rustup target add x86_64-unknown-linux-musl

WORKDIR /app

#create dependency layer to cache
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/lambda.rs
RUN cargo build --release --bin bootstrap --target x86_64-unknown-linux-musl || true

COPY src ./src
RUN cargo build --release --bin bootstrap --target x86_64-unknown-linux-musl
RUN strip /app/target/x86_64-unknown-linux-musl/release/bootstrap

FROM public.ecr.aws/lambda/provided:al2

WORKDIR /var/task

COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/bootstrap ./bootstrap

ARG ENVIRONMENT=prod
ARG APP_SERVER_HOST=0.0.0.0
ARG APP_SERVER_PORT=8080
ARG RUST_LOG=info

ENV ENVIRONMENT=$ENVIRONMENT
ENV APP_SERVER_HOST=$APP_SERVER_HOST
ENV APP_SERVER_PORT=$APP_SERVER_PORT
ENV RUST_LOG=$RUST_LOG

RUN chmod +x ./bootstrap

ENTRYPOINT ["sh", "-c", "echo 'Starting Lambda Bootstrap...' && ./bootstrap"]
