FROM rust:1.91-slim AS builder

RUN apt-get update && apt-get install -y musl-tools
RUN rustup target add x86_64-unknown-linux-musl

WORKDIR /app

#create dependency layer to cache
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/lambda.rs
RUN cargo build --release --bin bootstrap --target x86_64-unknown-linux-musl || true

COPY src ./src
RUN cargo build --release --bin bootstrap --target x86_64-unknown-linux-musl
RUN strip /app/target/x86_64-unknown-linux-musl/release/bootstrap

FROM public.ecr.aws/lambda/provided:al2

WORKDIR /var/task

COPY --from=builder /app/target/x86_64-unknown-linux-musl/release/bootstrap ./bootstrap

RUN chmod +x ./bootstrap

ENTRYPOINT [ "./bootstrap" ]
