FROM amazonlinux:2 AS builder

RUN yum update -y && \
    yum install -y gcc openssl-devel && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    yum clean all && \
    rm -rf /var/cache/yum
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

#create dependency layer to cache
COPY Cargo.toml Cargo.lock ./
RUN mkdir src && \
    echo "fn main() {}" > src/lambda.rs && \
    echo "" > src/lib.rs
RUN cargo build --release --bin bootstrap || true

COPY src ./src
RUN cargo build --release --bin bootstrap
RUN strip /app/target/release/bootstrap

FROM public.ecr.aws/lambda/provided:al2

WORKDIR /var/task

COPY --from=builder /app/target/release/bootstrap ./bootstrap

RUN chmod +x ./bootstrap

ENTRYPOINT [ "./bootstrap" ]
