FROM amazonlinux:2023 AS builder

RUN dnf update -y && \
    dnf install -y gcc openssl-devel tar gzip && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    dnf clean all
ENV PATH="/root/.cargo/bin:${PATH}"

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
RUN mkdir -p src/bin && \
    echo "fn main() {}" > src/bin/bootstrap_http.rs && \
    echo "// lib" > src/lib.rs
RUN cargo build --release --bin bootstrap_http --features http --no-default-features

COPY src ./src
RUN touch src/bin/bootstrap_http.rs src/lib.rs
RUN cargo build --release --bin bootstrap_http --features http --no-default-features

FROM public.ecr.aws/lambda/provided:al2023

WORKDIR /var/task

COPY --from=builder /app/target/release/bootstrap_http ./bootstrap

RUN chmod +x ./bootstrap

ENTRYPOINT [ "./bootstrap" ]
