name: Build and Push Docker Image to ECR

on:
  push:
    branches: dev
    paths-ignore:
      - "Docs/**"
  workflow_dispatch:

jobs:
  build-and-push-to-ecr-deploy-with-terraform:
    runs-on: ubuntu-latest
    environment: dev

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push HTTP image to Amazon ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.lambda.http
          push: true
          tags: |
            ${{ secrets.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:http-dev-${{ github.run_number }}
          cache-from: type=gha,scope=${{ github.ref }}-http
          cache-to: type=gha,scope=${{ github.ref }}-http,mode=max
          provenance: false

      - name: Build and push SQS image to Amazon ECR
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.lambda.sqs
          push: true
          tags: |
            ${{ secrets.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:sqs-dev-${{ github.run_number }}
          cache-from: type=gha,scope=${{ github.ref }}-sqs
          cache-to: type=gha,scope=${{ github.ref }}-sqs,mode=max
          provenance: false

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.11.2"

      - name: Deploy Dev Environment
        run: |
          cd terraform/dev
          terraform init
          terraform apply -auto-approve \
            -var="lambda_image_uri_http=${{ secrets.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:http-dev-${{ github.run_number }}" \
            -var="lambda_image_uri_sqs=${{ secrets.ECR_REGISTRY }}/${{ vars.ECR_REPOSITORY }}:sqs-dev-${{ github.run_number }}"
